# The Numpy.random package

***


1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python package.

To access NumPy and its functions it can be imported into your Python code like this:

import numpy as np

The imported name is shortened to np for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.

#### Arrays in numpy
While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

#### what is an array in numpy
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

[NumPy for absolute beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

#### examples of arrays

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [ ]:
print(a[1])

we can define an array without manually creating it

In [ ]:
# works with 'ones' also
np.zeros(11)

In [ ]:
#create an array with randon floats of a specified number 
#randomised- restart kernel to create new random numbers#
np.empty(5)

In [ ]:
# create an array with 40 elements
np.arange(40)

In [ ]:
# specify the first number, last number, and the step size
np.arange(2,33,2)

In [ ]:
#use np.linspace() to create an array with values that are spaced linearly in a specified interval
np.linspace(2,100, num=5)

In [ ]:
#default data type is floating point (np.float64) but if want e.g integer
x = np.ones(20, dtype=np.int64)
x
#e.g. no decimal points

sorting an array

In [ ]:
# array numbers are not sorted
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

In [ ]:
#array numbers are sorted by size
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

 also look-up: <br>
*argsort*, which is an indirect sort along a specified axis, <br>
*lexsort*, which is an indirect stable sort on multiple keys,<br>
*searchsorted*, which will find elements in a sorted array,<br>
*partition*, which is a partial sort<br>

#### concatenation of arrays

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])
np.concatenate ((a,b))

In [ ]:
#remember the double brackets
#new array lists elements in order called
np.concatenate ((b,a))

In [ ]:
# can concatenate one of the two arrays x times
np.concatenate ((b,b))

In [ ]:
# concatenate two arrays of different dimensions
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate ((x,y)) #, axis =0)

#### Dimensional arrays
An N-dimensional array is simply an array with any number of dimensions.<br> A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. 

In [ ]:
#dimensions within square brackets
#see below each array in square brackets is bracketed again- three of these
array_x = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]], 
                    
                    [[0 ,1 ,2, 3],
                     [4, 5, 6, 7]],
                    
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_x.ndim

In [ ]:
array_x.size

In [ ]:
# rows, columns
#dimensions, rows, columns
array_x.shape

reshape an array

In [ ]:
c= np.array([1, 2, 3,4,5,6])
b = c.reshape(3, 2)
b

<br>

#### Indexing & slicing (same as Python)

In [ ]:
# NumPy & Python count elements as: 0,1,2,3,4,5
data = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
data[1]

In [ ]:
data[1:4]

In [ ]:
data[3:]

In [ ]:
data[-2:]

In [ ]:
#print all the values in the array <5
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

In [ ]:
#write a function 'greater than four'
greater_than_four = (a >=5)
print(a[greater_than_four])

In [ ]:
#write a function 'greater than four' returns a boolean
greater_than_four = (a >=5)
print([greater_than_four])

In [ ]:
divisible_by_2 = a[a%2==0]
print([divisible_by_2])

In [ ]:
#apply two conditions
c = a[(a > 3) & (a < 9)]
print(c)

In [ ]:
# imagine the [] of a stacked on top of each other
# rows and columns then signify locations startign with row 0 and column 0 top left of dataframe
b = np.nonzero(a < 5)
print(b)

<br>

#### create an array from exisitng array

In [ ]:
# rcreate a new array from position 3 to 8 
# array numbering starts at zero
# element in position 3 is included , elmeent at position 8 is excluded
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

##### stacking arrays <br>

In [ ]:
# v stack = vertical stack
#Note: a1 = np.array  as below is the same i.e [2,2] on next line
#              ([[1, 1],
#                 [2, 2]])
a1 = np.array([[1, 1],[2, 2]])

a2 = np.array([[3, 3],[4, 4]])

np.vstack((a1, a2))

In [ ]:
# or can stack them horizontally so that 1st row of 1st array then 1st row of 2nd array etc
np.hstack((a1, a2))

In [ ]:
# create two arrays using elements 1-24
x = np.arange(1, 25).reshape(2, 12)
x

In [ ]:
#reshape: split into three dimensions
np.hsplit(x, 3)

In [ ]:
#array_x.ndim
array_x.shape
#array_x.size

In [ ]:
# split the two arrays in x after 3rd and 4th column:
np.hsplit(x, (3, 4))

In [ ]:
# split the two arrays in x after 3rd,4th and 5th column:
np.hsplit(x, (3, 4, 5))

In [ ]:
# split the two arrays  in x  after 3rd to 11th column:
np.hsplit(x, (2,3,4,5,6,7,8,9,10,11))

In [ ]:
ax = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = ax[1, :]
b1

In [ ]:
b1[1:3] = 99, 100

In [ ]:
b1

In [ ]:
#note original array has changed too
#could use copy i.e. b2 = a.copy() and work from there
ax

#### add and subtract array elements

In [ ]:
# 'data' = [1,2] , ones = [1,1]
#dtype int = data type integer otherwise ones will create float numbers
#arrays have to have same number of elements
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

In [ ]:
data - ones

In [ ]:
data * data

In [ ]:
data / data

In [ ]:
a = np.array([1, 2, 3, 4])
a.sum()

In [ ]:
# prodct of array i.e.1*2*3*4=24 
a.prod()

In [ ]:
a.max()

In [ ]:
a.mean()

In [ ]:
# three rows of data each containing 3 entriels i.e. 4 columns
# Axis 0 = looking down vertically through the elements
# axis 1 = looking horizontally across the elements
#   C1 C2 C3 C4
#R1 1  1  5  8
#R2 2  2  6  10
#R3 2  5  6  8
b = np.array([[1, 1,5,8], [2, 2, 6, 10], [2, 5, 6, 8]])
b.sum(axis=0)

In [ ]:
b.sum(axis=1)

#### broadcasting

NumPy understands that the multiplication should happen with each cell.<br> That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. <br> The dimensions of your array must be compatible, <br> for example, when the dimensions of both arrays are equal or when one of them is 1. <br> If the dimensions are not compatible, you will get a ValueError<br> 

In [ ]:
# e.g. convert all array elelemts from miles to km
miles = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
miles * 1.6

In [ ]:
# whats the min looking top down
miles.min(axis =0)

In [ ]:
# whats the min looking across
miles.min(axis =1)

<br>

#### creating matrices from arrays
https://www.programiz.com/python-programming/matrix

In [ ]:
 #array([[1, 2,1],
      # [3, 10,1],
      # [5, 6,1]])
    
data = np.array([[1, 2,1], [3, 10,1], [5, 6,1]])
# 1st row, 2nd value from left
data[0, 1]

In [ ]:
# 1st, 2nd and 3rd row (0,1,2) - 1st element in each
data[0:3, 0]

In [ ]:
data[0:3, 2]

In [ ]:
data.max()

In [ ]:
# axis =0 analyses the array vertically (look down each column)
data.max(axis=0)

In [ ]:
# axis =1 analyses the array horizontally (look across each row)
data.max(axis=1)

In [ ]:
data.min(axis=1)

In [ ]:
data_add = np.array([[1, 1, 20],[1, 1, 20], [1, 1,20]])
data+data_add

<br>

#### Random Number Generation with NumPy
[NumPy Random Number Generator](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) <br>
[W3 Schools]('https://www.w3schools.com/python/numpy/numpy_random.asp') <br>
[PythonGuides]('https://pythonguides.com/python-numpy-random/')

<br>

#### What is random number in python numpy?
Random numbers are the numbers that return a random integer.<br> The random number does not mean a different number every time.<br> Random means something that cannot be predicted logically.<br>Python numpy random
In Python random is a module that is available in the NumPy library. <br> This module returns an array of specified shapes and fills it with random floats and integers.<br> 
It is based on pseudo-random number generation that means it is a mathematical way that generates a sequence of nearly random numbers<br> 
In Python, the numpy library provides a module called random that will help the user to generate a random number.<br> 
In Python, the randint() function always returns a random integer number between the lower and the higher limits these both limits are the parameters of the randint() function.<br> 

https://pythonguides.com/python-numpy-random/

In [ ]:
np.ones(3)

In [ ]:
np.zeros(3)

In [ ]:
x = np.zeros(24).reshape(4, 6)
x

#### Np.randon.default_rng

In [ ]:
#np.random.default_rng

In [ ]:
# the simplest way to generate random numbers
#Note remains the same random numbers until kernel is reset
rng = np.random.default_rng(0)
rng.random(3)

In [ ]:
#rng is random number generator
rng = np.random.default_rng(12345)
print(rng)

#### Return Arrays of random integers

In [ ]:
rng = np.random.default_rng()
rng.integers(1, size=10)

In [ ]:
# Syntax: Max value , array size
rng = np.random.default_rng()
rng.integers(12, size=10)

In [ ]:
# 'seed' the rng with a value. The assay returned is the same unless the 'seeded' value is changed
rng = np.random.default_rng(1234)
rints = rng.integers(low=0, high=10, size=3)
rints

In [ ]:
# define the size and shape
rng.integers(5, size=(2, 4))

In [ ]:
# seeding
# run it again and you get the same 'random' values in the array
# change the seed ands re-run it: new random numbers in array
rng = np.random.default_rng(seed=42)
arr2 = rng.random((4, 4))
arr2

In [ ]:
rng.integers(100, size=100)

In [ ]:
x = rng.integers(100, size=10000)
x

In [ ]:
# syntax: lowest number, highest number, array size to return
import random
result = np.random.randint(20,30,5)
result

In [ ]:
# numpy random function can create a random mumber without restart kernel
from numpy import random
x= random.randint(20,30,5)
print(x)

#### randrange
##### return an integer

In [147]:
#returns an integerfrom random import randrange
print(randrange(20))

14


#### random float
***

In [ ]:
# if don't require a whole number (integer) numpy can return a random float
val = random.rand()
print (val)

#### generate a randon number from an array random.choice

In [151]:
# returns one of the array elements- once re-run
val = random.choice([40,5,66,8])
val

5

In [152]:
random_num = np.random.choice(18)
print (" The random number is : ")
print (random_num)

 The random number is : 
16


#### Numpy Random.Randn

In [159]:
random_num = np.random.randn(18)
print (" The random numbers are: \n\n")
print (random_num)

 The random numbers are: 


[ 1.32984309  0.60843085  0.27375026  1.84655323 -1.06661048  1.72886323
  0.25166084  0.76518324 -1.46208458 -0.77263844 -0.21451952 -0.10725513
  0.03691323  1.75547058  0.37040254  0.09786102 -2.52872693  1.09505194]


In [161]:
random_num = np.random.random_sample(18)
print (" The following are a random sample of numbers: \n\n")
print (random_num)

 The following are a random sample of numbers: 


[0.27256044 0.67763443 0.72049876 0.13182343 0.45262984 0.04853347
 0.00525021 0.79863834 0.49547031 0.53575607 0.75956904 0.78920769
 0.88366957 0.68323295 0.85096296 0.67180822 0.98457258 0.1320093 ]


In [164]:
random_num = np.random.uniform(0,1,10)
print (" The following is an array of specified size filled with random numbers: \n\n")
print (random_num)

 The following is an array of specified size filled with random numbers: 


[0.43940058 0.41166741 0.44387271 0.88486034 0.78207257 0.19657919
 0.55689979 0.40062571 0.50901424 0.29750013]


In [168]:
random_num = np.random.randint(30, size=10)
print (random_num)

[19  3 18 15  2 27 18 27 13 18]


In [170]:
# create an array of randint
random_num = np.random.randint(30, size=(8,10))
print (random_num)

[[20 26  3 27 17 10 17 13  4  2]
 [10  5  7 26 27 28 20 18  6 22]
 [ 8 16 22  8 23  8 19 29 19  5]
 [ 4 28 20 20 24 18 18  8 15 14]
 [16 25 28  0 20  2  4 17 27  9]
 [23  4 26 10  7  6  9 19 27  2]
 [24 18 16 19 28  8 13 21 23 28]
 [ 5 26  1  6 19  9 13  6 26 16]]


#### Seeding (Python Numpy Random Seed)

Numpy random seed is used to set the seed and to generate pseudo-random numbers. <br> A pseudo-random number is a number that sorts random, but they are not really random.<br>
In Python, the seed value is the previous value implemented by the generator. <br>If there is no previous value then NumPy uses the working system time.<br>
Rationale for the random seed is to get the same set of random numbers for the given seed.<br>

In [171]:
np.random.seed(5)
new_val = np.random.randint(2,6)
print(new_val)

5


# stopped here

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#matplotlib inline # magic command if histogram doesn't show
plt.hist(x)
plt.show() # may not be needed but again insert if not showing in notebook

[essential tips for writing with Jupyter Notebooks](https://towardsdatascience.com/7-essential-tips-for-writing-with-jupyter-notebook-60972a1a8901)